openapi: 3.0.1
info:
  title: API de Exemplo
  description: Documentação Swagger para endpoints CRUD de Customer e Product
  version: 1.0.0

components:
  schemas:
    RegisterCustomerRequest:
      type: object
      properties:
        name:
          type: string
        lastName:
          type: string
        age:
          type: integer
          format: int32
        email:
          type: string
          format: email
    RegisterCustomerResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
    UpdateCustomerRequest:
      type: object
      properties:
        name:
          type: string
        lastName:
          type: string
        age:
          type: integer
          format: int32
        email:
          type: string
          format: email
    SearchCustomerResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        lastName:
          type: string
        age:
          type: integer
          format: int32
        email:
          type: string
          format: email
paths:
  /customers:
    get:
      summary: Lista todos os clientes
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SearchCustomerResponse'
    post:
      summary: Cria um novo cliente
      requestBody:
        description: Dados do cliente a serem criados
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterCustomerRequest'
      responses:
        '201':
          description: Cliente criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterCustomerResponse'
  /customers/{customerId}:
    get:
      summary: Retorna detalhes de um cliente específico
      parameters:
        - name: customerId
          in: path
          required: true
          description: ID do cliente
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchCustomerResponse'
    put:
      summary: Atualiza um cliente existente
      parameters:
        - name: customerId
          in: path
          required: true
          description: ID do cliente
          schema:
            type: integer
            format: int64
      requestBody:
        description: Dados do cliente a serem atualizados
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCustomerRequest'
      responses:
        '204':
          description: Cliente atualizado com sucesso
    delete:
      summary: Exclui um cliente
      parameters:
        - name: customerId
          in: path
          required: true
          description: ID do cliente
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Cliente excluído com sucesso